# LTEsim Parameter Module
#
# Copyright Ericsson AB 2013.
#
# This example shows how to setup and retrieve configuration parameters for LTEsim.
#

#
# Module that contains functions for retrieving configuration values for the LTEsim components.
#
# Copy this file to your home directory with a different name and edit the copy
# to match your environment.
#
# Make sure that your version of parameters.rb is used by one of the following methods:
#
#   Start ltesim_cli with the parameter -params <file>
#
#   Start ltesim_cli in the same folder as your file %parameters.rb
#
#   Add the folder with parameters.rb to the ltesim_cli search path, using the -p parameter
#
#   Load your parameters.rb file in each test script (or in the ltesim_cli) by adding
#   "LteSimCli.rerequire '<path to and including parameters.rb>'" in the beginning of the script.
#
require 'etc'
module Parameters
  #
  # Retrieve general configuration parameters.
  #
  def Parameters.getGeneralParameters()
    # Define and return default values
    default = {}

    # Create new log directory for each run
    log_dir = "-l /tmp/" + Etc.getlogin() + "_" + Time.new.strftime("%Y%m%d_%H%M%S")
    default[:coreParameters] = "#{log_dir}"   # String containing start parameters for ltesim core
                                              # See ltesim core -help for details

    default[:jvm_parameters] = ""             # Specify additional JVM parameters

    default[:logger_handlersSet] = "com.ericsson.cctt.log.RollingGzFileHandler"
    default[:logger_file_count] = 20
    default[:logger_file_sizeLimit] = 2**30   # 2**30 = 1 GiB
    default[:logger_file_gzipEnabled] = true  # enables gzip of rotated logs

    # All JMX parameters can be listed with help :launcher in the ltesim_cli
    return default
  end


  #
  # Retrieve default parameters for MME.
  #
  def Parameters.getMmeParameters()
    # Define and return default values
    default = {}

    default[:simulate_core] = false           # Set to true if simulated core is used in the configuration.
    default[:mme_names] = ["mme1"]            # Name of the MME component
    default[:mme_tais] = ["62F2281200"]       # MME tracking area identity value
    default[:mmes] = 1                        # Number of MMEs (used in multiple MME configuration)

    # The IP addresses must be available on the LTEsim server and reachable from the eNB CP interface
    default[:mme_s1ap_uris] = ["sctp://127.0.0.1:36412"]
    default[:s1ap_pluginFilterPath] = "/etc/alternatives/ltesim-root/ltesim/internal/ltesim-plugin-filters/com/ericsson/sps/ltesim/s1ap/filter"  # Set the filter path

    # All JMX parameters can be listed with help :mme in the ltesim_cli
    return default
  end


  #
  # Retrieve default parameters for Paging generator.
  #
  def Parameters.getPagingGeneratorParameters()
    # Define and return default values
    default = {}

    default[:generate_pagings] = false        # Set to true if paging generators are used in the configuration.
    default[:generators] = 3                  # Number of paging generators
    default[:paging_generator_names] = ["pagings1", "pagings2", "pagings3"]  # Name of the paging generators
    default[:imsi_ranges] = ["100000+100", "200000+100", "300000+100"]  # The IMSI range which pagings are generated by each generator.
    default[:ue_paging_identity] = "IMSI" # Can be IMSI or STMSI

    # The IP addresses must be available on the LTEsim server and reachable from the eNB CP interface
    default[:paging_s1ap_uris] = ["sctp://127.0.1.1:36412", "sctp://127.0.1.2:36412", "sctp://127.0.1.3:36412"]

    default[:bundle_paging] = false           # Set constraint check to true to turn paging bundle.
    # All JMX parameters can be listed with help :paginggenerator in the ltesim_cli
    return default
  end


  #
  # Retrieve default parameters for SGW.
  #
  def Parameters.getSgwParameters()
    # Define and return default values
    default = {}

    default[:sgw_names] = ["sgw1"]            # Name of the Serving GWs
    default[:sgw_ipAddresses] = ["127.0.0.1"]
    default[:apn_lists] = ["ltesim-core-network,172.17.0.1/16;"]
    default[:sgw_LDIs] = ["30"]
    default[:core_network_gateway] = false    # Indicates if the core network shall act
                                              # as an IP gateway to the UEs

    # All JMX parameters can be listed with help :sgw in the ltesim_cli
    return default
  end


  #
  # Retrieve default parameters for UE component, including L1L2 Manager
  # configuration parameters.
  #
  def Parameters.getUeParameters()
    # Define and return default values
    default = {}

    default[:start_ue_component] = true       # Decide if the UE component should be started

    default[:name] = "ue1"                    # Name of the UE component

    default[:l1l2_managers] = "UCTOOL;uctool1"  # Space separated string with TYPE;instance tuples where allowed values of TYPE is UCTOOL.
    default[:rrc_pluginFilterPath] = "/etc/alternatives/ltesim-root/ltesim/internal/ltesim-plugin-filters/com/ericsson/sps/ltesim/ue/rrc/filter"

    # UCTool specific parameters
    default[:uctool_ip] = "{uctool1;192.168.3.5}"           # UCTOOL device name the IP address of the UCtool.
                                                            # NOTE! If only IP address is given then the IP address will be
                                                            # applicable for all UCTOOL managers.
    default[:uctool_cIds] = "{uctool1;cell11,cell12}"       # UCTOOL device name and cell names used to map.
                                                            # the UCTOOL cells to corresponding cells in the REC.
    default[:uctool_service_ip] = "{uctool1;192.168.3.19}"  # UCTOOL device name and the IP address of the service requested.
                                                            # NOTE! If only IP address is given then the IP address will be
                                                            # applicable for all UCTOOLs.

    ###### Security related parameters ###################################################################################
    default[:ue_network_capability] = "E0E0"                # UE network capabilities. See 3GPP 24.008 for more details
                                                            # Used to control which integrity protection and ciphering algorithms a UE supports.

    default[:ue_keyDerivationAlgorithm] = "TEST_ALGORITHM"  # The algorithm used during EPS AKA procedure.
                                                            # Supported algorithms:
                                                            # * TEST_ALGORITHM - The test algorithm defined in TS 34.108.
                                                            # * MILENAGE - The milenage algorithm defined in TS 35.205.
                                                            # Also used in simulated MME.

    default[:ue_key] = "000102030405060708090A0B0C0D0E0F"   # The shared secret key between the UE and MME. Also used in simulated MME.

    #default[:ue_keyDerivationAlgorithm] = "MILENAGE"       # Used for MILENAGE
    #default[:ue_key] = "77777777777777777777777777777777"  # Used for MILENAGE
    default[:ue_op] = "CDC202D5123E20F62B6D676AC72CB318"    # The OP used in the MILENAGE algorithm. Also used in simulated MME.
    ######################################################################################################################

    # All JMX parameters can be listed with help :ue in the ltesim_cli
    return default
  end


  #
  # Retrieve default parameters for Radio Environment.
  #
  def Parameters.getRecParameters()
    # Define and return default values
    default = {}

    # Write with the following syntax:
    # default[:rec] = [{<first set of cell params>},{<second set of cell params>}]
    #
    # A set of cell params includes:
    #   :cell                    # Cell instance name
    #   :site                    # Site instance name
    #   :pci                     # Physical cell identifier
    #   :position_X              # Cell position, coordinate X
    #   :position_Y              # Cell position, coordinate Y
    #   :earfcnDl                # Channel number for the central DL frequency
    #   :transmitPower           # Transmit power in dBm
    #   :ulNoiseAndInterference  # uplink N+I in dBm
    default[:rec] = [
      {
        :cell => "cell11",
        :site => "site11",
        :pci => 11,
        :position_X => 7000,
        :position_Y => 7000,
        :earfcnDl => 2050,
        :transmitPower => -75.0,
        :ulNoiseAndInterference => -116.0
      },{
        :cell => "cell12",
        :site => "site12",
        :pci => 12,
        :position_X => 14000,
        :position_Y => 7000,
        :earfcnDl => 2050,
        :transmitPower => -75.0,
        :ulNoiseAndInterference => -116.0
      },{
        :cell => "cell13",
        :site => "site13",
        :pci => 13,
        :position_X => 21000,
        :position_Y => 7000,
        :earfcnDl => 2050,
        :transmitPower => -75.0,
        :ulNoiseAndInterference => -116.0
      },{
        :cell => "cell14",
        :site => "site14",
        :pci => 14,
        :position_X => 28000,
        :position_Y => 7000,
        :earfcnDl => 2050,
        :transmitPower => -75.0,
        :ulNoiseAndInterference => -116.0
      },{
        :cell => "cell21",
        :site => "site21",
        :pci => 21,
        :position_X => 10500,
        :position_Y => 13000,
        :earfcnDl => 2050,
        :transmitPower => -75.0,
        :ulNoiseAndInterference => -116.0
      },{
        :cell => "cell22",
        :site => "site22",
        :pci => 22,
        :position_X => 17500,
        :position_Y => 13000,
        :earfcnDl => 2050,
        :transmitPower => -75.0,
        :ulNoiseAndInterference => -116.0
      },{
        :cell => "cell23",
        :site => "site23",
        :pci => 23,
        :position_X => 24500,
        :position_Y => 13000,
        :earfcnDl => 2050,
        :transmitPower => -75.0,
        :ulNoiseAndInterference => -116.0
      },{
        :cell => "cell24",
        :site => "site24",
        :pci => 24,
        :position_X => 31500,
        :position_Y => 13000,
        :earfcnDl => 2050,
        :transmitPower => -75.0,
        :ulNoiseAndInterference => -116.0
      },{
        :cell => "cell31",
        :site => "site31",
        :pci => 31,
        :position_X => 7000,
        :position_Y => 19000,
        :earfcnDl => 2050,
        :transmitPower => -75.0,
        :ulNoiseAndInterference => -116.0
      },{
        :cell => "cell32",
        :site => "site32",
        :pci => 32,
        :position_X => 14000,
        :position_Y => 19000,
        :earfcnDl => 2050,
        :transmitPower => -75.0,
        :ulNoiseAndInterference => -116.0
      },{
        :cell => "cell33",
        :site => "site33",
        :pci => 33,
        :position_X => 21000,
        :position_Y => 19000,
        :earfcnDl => 2050,
        :transmitPower => -75.0,
        :ulNoiseAndInterference => -116.0
      },{
        :cell => "cell34",
        :site => "site34",
        :pci => 34,
        :position_X => 28000,
        :position_Y => 19000,
        :earfcnDl => 2050,
        :transmitPower => -75.0,
        :ulNoiseAndInterference => -116.0
      },{
        :cell => "cell41",
        :site => "site41",
        :pci => 41,
        :position_X => 10500,
        :position_Y => 25000,
        :earfcnDl => 2050,
        :transmitPower => -75.0,
        :ulNoiseAndInterference => -116.0
      },{
        :cell => "cell42",
        :site => "site42",
        :pci => 42,
        :position_X => 17500,
        :position_Y => 25000,
        :earfcnDl => 2050,
        :transmitPower => -75.0,
        :ulNoiseAndInterference => -116.0
      },{
        :cell => "cell43",
        :site => "site43",
        :pci => 43,
        :position_X => 24500,
        :position_Y => 25000,
        :earfcnDl => 2050,
        :transmitPower => -75.0,
        :ulNoiseAndInterference => -116.0
      },{
        :cell => "cell44",
        :site => "site44",
        :pci => 44,
        :position_X => 31500,
        :position_Y => 25000,
        :earfcnDl => 2050,
        :transmitPower => -75.0,
        :ulNoiseAndInterference => -116.0
      },{
        :cell => "cell51",
        :site => "site51",
        :pci => 51,
        :position_X => 7000,
        :position_Y => 31000,
        :earfcnDl => 2050,
        :transmitPower => -75.0,
        :ulNoiseAndInterference => -116.0
      },{
        :cell => "cell52",
        :site => "site52",
        :pci => 52,
        :position_X => 14000,
        :position_Y => 31000,
        :earfcnDl => 2050,
        :transmitPower => -75.0,
        :ulNoiseAndInterference => -116.0
      },{
        :cell => "cell53",
        :site => "site53",
        :pci => 53,
        :position_X => 21000,
        :position_Y => 31000,
        :earfcnDl => 2050,
        :transmitPower => -75.0,
        :ulNoiseAndInterference => -116.0
      },{
        :cell => "cell54",
        :site => "site54",
        :pci => 54,
        :position_X => 28000,
        :position_Y => 31000,
        :earfcnDl => 2050,
        :transmitPower => -75.0,
        :ulNoiseAndInterference => -116.0
      },{
        :cell => "cell61",
        :site => "site61",
        :pci => 61,
        :position_X => 10500,
        :position_Y => 37000,
        :earfcnDl => 2050,
        :transmitPower => -75.0,
        :ulNoiseAndInterference => -116.0
      },{
        :cell => "cell62",
        :site => "site62",
        :pci => 62,
        :position_X => 17500,
        :position_Y => 37000,
        :earfcnDl => 2050,
        :transmitPower => -75.0,
        :ulNoiseAndInterference => -116.0
      },{
        :cell => "cell63",
        :site => "site63",
        :pci => 63,
        :position_X => 24500,
        :position_Y => 37000,
        :earfcnDl => 2050,
        :transmitPower => -75.0,
        :ulNoiseAndInterference => -116.0
      },{
        :cell => "cell64",
        :site => "site64",
        :pci => 64,
        :position_X => 31500,
        :position_Y => 37000,
        :earfcnDl => 2050,
        :transmitPower => -75.0,
        :ulNoiseAndInterference => -116.0
      }
    ]
    return default
  end


  #
  # Retrieve default parameters for user behavior models
  #
  def Parameters.getTraffBehaviourParameters()
    # Define and return default values
    default = {}

    # IMSI range used by traffic models.
    # IMSI ranges are specified with the
    # following syntax (space separated string):
    # "<first_range> <second_range>".
    default[:imsiMapRange] = "1122334455+3999"

    # Size of geographical map
    default[:southBoundMap] = 0
    default[:northBoundMap] = 43000
    default[:westBoundMap] = 0
    default[:eastBoundMap] = 38500

    # Areas defined which are possible to use with traffic models (aka Cell Map)
    #
    # :area - naming convention for three types of areas:
    #   Center     an area with a RBS cell in the center
    #   Handover   an area with two RBS:es
    #   Common     an area containing all cells
    # Center:
    #   :area => "Center11"             # Area name around cell1-1 (RBS-1)
    #                    ^--- cell number
    #                   ^--- RBS number
    # Handover:
    #   :area => "Handover11_21"        # Area name for possible inter handover between RBS-1 and RBS-2
    #                         ^--- cell number
    #                        ^--- RBS number
    #                      ^--- cell number
    #                     ^--- RBS number
    # Common:
    #   :area => "Common",              # Area common for all cells
    #
    # Boundaries, specified for all types of areas:
    #   :southBoundary => 6900,         # South boundary of area
    #   :northBoundary => 7100,         # North boundary of area
    #   :westBoundary => 6900,          # West boundary of area
    #   :eastBoundary => 7100,          # East boundary of area
    default[:areas] = [
      {
        :area => "Center11",
        :southBoundary => 6900,
        :northBoundary => 7100,
        :westBoundary => 6900,
        :eastBoundary => 7100
      },{
        :area => "Center12",
        :southBoundary => 6900,
        :northBoundary => 7100,
        :westBoundary => 13900,
        :eastBoundary => 14100
      },{
        :area => "Center13",
        :southBoundary => 6900,
        :northBoundary => 7100,
        :westBoundary => 20900,
        :eastBoundary => 21100
      },{
        :area => "Center14",
        :southBoundary => 6900,
        :northBoundary => 7100,
        :westBoundary => 27900,
        :eastBoundary => 28100
      },{
        :area => "Center21",
        :southBoundary => 12900,
        :northBoundary => 13100,
        :westBoundary => 10400,
        :eastBoundary => 10600
      },{
        :area => "Center22",
        :southBoundary => 12900,
        :northBoundary => 13100,
        :westBoundary => 17400,
        :eastBoundary => 17600
      },{
        :area => "Center23",
        :southBoundary => 12900,
        :northBoundary => 13100,
        :westBoundary => 24400,
        :eastBoundary => 24600
      },{
        :area => "Center24",
        :southBoundary => 12900,
        :northBoundary => 13100,
        :westBoundary => 31400,
        :eastBoundary => 31600
      },{
        :area => "Center31",
        :southBoundary => 18900,
        :northBoundary => 19100,
        :westBoundary => 6900,
        :eastBoundary => 7100
      },{
        :area => "Center32",
        :southBoundary => 18900,
        :northBoundary => 19100,
        :westBoundary => 13900,
        :eastBoundary => 14100
      },{
        :area => "Center33",
        :southBoundary => 18900,
        :northBoundary => 19100,
        :westBoundary => 20900,
        :eastBoundary => 21100
      },{
        :area => "Center34",
        :southBoundary => 18900,
        :northBoundary => 19100,
        :westBoundary => 27900,
        :eastBoundary => 28100
      },{      
        :area => "Center41",
        :southBoundary => 24900,
        :northBoundary => 25100,
        :westBoundary => 10400,
        :eastBoundary => 10600
      },{
        :area => "Center42",
        :southBoundary => 24900,
        :northBoundary => 25100,
        :westBoundary => 17400,
        :eastBoundary => 17600
      },{
        :area => "Center43",
        :southBoundary => 24900,
        :northBoundary => 25100,
        :westBoundary => 24400,
        :eastBoundary => 24600
      },{
        :area => "Center44",
        :southBoundary => 24900,
        :northBoundary => 25100,
        :westBoundary => 31400,
        :eastBoundary => 31600
      },{
        :area => "Center51",
        :southBoundary => 30900,
        :northBoundary => 31100,
        :westBoundary => 6900,
        :eastBoundary => 7100
      },{
        :area => "Center52",
        :southBoundary => 30900,
        :northBoundary => 31100,
        :westBoundary => 13900,
        :eastBoundary => 14100
      },{
        :area => "Center53",
        :southBoundary => 30900,
        :northBoundary => 31100,
        :westBoundary => 20900,
        :eastBoundary => 21100
      },{
        :area => "Center54",
        :southBoundary => 30900,
        :northBoundary => 31100,
        :westBoundary => 27900,
        :eastBoundary => 28100
      },{
        :area => "Center61",
        :southBoundary => 36900,
        :northBoundary => 37100,
        :westBoundary => 10400,
        :eastBoundary => 10600
      },{
        :area => "Center62",
        :southBoundary => 36900,
        :northBoundary => 37100,
        :westBoundary => 17400,
        :eastBoundary => 17600
      },{
        :area => "Center63",
        :southBoundary => 36900,
        :northBoundary => 37100,
        :westBoundary => 24400,
        :eastBoundary => 24600
      },{
        :area => "Center64",
        :southBoundary => 36900,
        :northBoundary => 37100,
        :westBoundary => 31400,
        :eastBoundary => 31600
      },{
        :area => "Handover11_21",
        :southBoundary => 7750,
        :northBoundary => 12250,
        :westBoundary => 8000,
        :eastBoundary => 9000
      },{
        :area => "Handover11_12",
        :southBoundary => 6500,
        :northBoundary => 7500,
        :westBoundary =>  8250,
        :eastBoundary => 12750
      },{
        :area => "Handover12_21",
        :southBoundary => 7750,
        :northBoundary => 12250,
        :westBoundary =>  11500,
        :eastBoundary => 12500
      },{
        :area => "Handover12_22",
        :southBoundary => 7750,
        :northBoundary => 12250,
        :westBoundary =>  15000,
        :eastBoundary => 16000
      },{
        :area => "Handover21_22",
        :southBoundary => 12500,
        :northBoundary => 13500,
        :westBoundary =>  11750,
        :eastBoundary => 16250
      },{
        :area => "Handover31_32",
        :southBoundary => 18500,
        :northBoundary => 19500,
        :westBoundary =>  8250,
        :eastBoundary => 12750
      },{
        :area => "Handover21_31",
        :southBoundary => 13750,
        :northBoundary => 18250,
        :westBoundary => 8000,
        :eastBoundary => 9000
      },{
        :area => "Handover21_32",
        :southBoundary => 13750,
        :northBoundary => 18250,
        :westBoundary => 11500,
        :eastBoundary => 12500
      },{
        :area => "Handover22_32",
        :southBoundary => 13750,
        :northBoundary => 18250,
        :westBoundary => 15000,
        :eastBoundary => 16000
      },{
        :area => "Handover41_42",
        :southBoundary => 24500,
        :northBoundary => 25500,
        :westBoundary => 11750,
        :eastBoundary => 16250
      },{
        :area => "Handover41_51",
        :southBoundary => 25750,
        :northBoundary => 30250,
        :westBoundary => 8000,
        :eastBoundary => 9000
      },{
        :area => "Handover51_52",
        :southBoundary => 30500,
        :northBoundary => 31500,
        :westBoundary => 8250,
        :eastBoundary => 12750
      },{
        :area => "Handover61_62",
        :southBoundary => 36500,
        :northBoundary => 37500,
        :westBoundary => 11750,
        :eastBoundary => 16250
      },{
        :area => "Handover31_41",
        :southBoundary => 19750,
        :northBoundary => 24250,
        :westBoundary => 8000,
        :eastBoundary => 9000
      },{
        :area => "Handover32_41",
        :southBoundary => 19750,
        :northBoundary => 24250,
        :westBoundary => 11500,
        :eastBoundary => 12500
      },{
        :area => "Handover32_42",
        :southBoundary => 19750,
        :northBoundary => 24250,
        :westBoundary => 15000,
        :eastBoundary => 16000
      },{
        :area => "Handover41_52",
        :southBoundary => 25750,
        :northBoundary => 30250,
        :westBoundary => 11500,
        :eastBoundary => 12500
      },{
        :area => "Handover42_52",
        :southBoundary => 25750,
        :northBoundary => 30250,
        :westBoundary => 15000,
        :eastBoundary => 16000
      },{
        :area => "Handover51_61",
        :southBoundary => 31750,
        :northBoundary => 36250,
        :westBoundary => 8000,
        :eastBoundary => 9000
      },{
        :area => "Handover52_61",
        :southBoundary => 31750,
        :northBoundary => 36250,
        :westBoundary => 11500,
        :eastBoundary => 12500
      },{
        :area => "Handover52_62",
        :southBoundary => 31750,
        :northBoundary => 36250,
        :westBoundary => 15000,
        :eastBoundary => 16000
      },{
        :area => "Handover12_13",
        :southBoundary => 6500,
        :northBoundary => 7500,
        :westBoundary => 15250,
        :eastBoundary => 19750
      },{
        :area => "Handover13_14",
        :southBoundary => 6500,
        :northBoundary => 7500,
        :westBoundary => 22250,
        :eastBoundary => 26750
      },{
        :area => "Handover22_23",
        :southBoundary => 12500,
        :northBoundary => 13500,
        :westBoundary => 18750,
        :eastBoundary => 23250
      },{
        :area => "Handover23_24",
        :southBoundary => 12500,
        :northBoundary => 13500,
        :westBoundary => 25750,
        :eastBoundary => 30250
      },{
        :area => "Handover32_33",
        :southBoundary => 18500,
        :northBoundary => 19500,
        :westBoundary => 15250,
        :eastBoundary => 19750
      },{
        :area => "Handover33_34",
        :southBoundary => 18500,
        :northBoundary => 19500,
        :westBoundary => 22250,
        :eastBoundary => 26750
      },{
        :area => "Handover42_43",
        :southBoundary => 24500,
        :northBoundary => 25500,
        :westBoundary => 18750,
        :eastBoundary => 23250
      },{
        :area => "Handover43_44",
        :southBoundary => 24500,
        :northBoundary => 25500,
        :westBoundary => 25750,
        :eastBoundary => 30250
      },{
       :area => "Handover52_53",
        :southBoundary => 30500,
        :northBoundary => 31500,
        :westBoundary => 15250,
        :eastBoundary => 19750
      },{
       :area => "Handover53_54",
        :southBoundary => 30500,
        :northBoundary => 31500,
        :westBoundary => 22250,
        :eastBoundary => 26750
      },{
        :area => "Handover62_63",
        :southBoundary => 36500,
        :northBoundary => 37500,
        :westBoundary => 18750,
        :eastBoundary => 23250
      },{
        :area => "Handover63_64",
        :southBoundary => 36500,
        :northBoundary => 37500,
        :westBoundary => 25750,
        :eastBoundary => 30250
      },{
        :area => "Handover13_22",
        :southBoundary => 7750,
        :northBoundary => 12250,
        :westBoundary =>  18500,
        :eastBoundary => 19500
      },{
        :area => "Handover13_23",
        :southBoundary => 7750,
        :northBoundary => 12250,
        :westBoundary =>  22000,
        :eastBoundary => 23000
      },{
        :area => "Handover14_23",
        :southBoundary => 7750,
        :northBoundary => 12250,
        :westBoundary =>  25500,
        :eastBoundary => 26500
      },{
        :area => "Handover14_24",
        :southBoundary => 7750,
        :northBoundary => 12250,
        :westBoundary =>  29000,
        :eastBoundary => 30000
      },{
        :area => "Handover22_33",
        :southBoundary => 13750,
        :northBoundary => 18250,
        :westBoundary => 18500,
        :eastBoundary => 19500
      },{
        :area => "Handover23_33",
        :southBoundary => 13750,
        :northBoundary => 18250,
        :westBoundary => 22000,
        :eastBoundary => 23000
      },{
        :area => "Handover23_34",
        :southBoundary => 13750,
        :northBoundary => 18250,
        :westBoundary => 25500,
        :eastBoundary => 26500
      },{
        :area => "Handover24_34",
        :southBoundary => 13750,
        :northBoundary => 18250,
        :westBoundary => 29000,
        :eastBoundary => 30000
      },{
        :area => "Handover33_42",
        :southBoundary => 19750,
        :northBoundary => 24250,
        :westBoundary => 18500,
        :eastBoundary => 19500
      },{
        :area => "Handover33_43",
        :southBoundary => 19750,
        :northBoundary => 24250,
        :westBoundary => 22000,
        :eastBoundary => 23000
      },{
        :area => "Handover34_43",
        :southBoundary => 19750,
        :northBoundary => 24250,
        :westBoundary => 25500,
        :eastBoundary => 26500
      },{ 
        :area => "Handover34_44",
        :southBoundary => 19750,
        :northBoundary => 24250,
        :westBoundary => 29000,
        :eastBoundary => 30000
      },{
        :area => "Handover42_53",
        :southBoundary => 25750,
        :northBoundary => 30250,
        :westBoundary => 18500,
        :eastBoundary => 19500
      },{
        :area => "Handover43_53",
        :southBoundary => 25750,
        :northBoundary => 30250,
        :westBoundary => 22000,
        :eastBoundary => 23000
      },{
        :area => "Handover43_54",
        :southBoundary => 25750,
        :northBoundary => 30250,
        :westBoundary => 25500,
        :eastBoundary => 26500
      },{
        :area => "Handover44_54",
        :southBoundary => 25750,
        :northBoundary => 30250,
        :westBoundary => 29000,
        :eastBoundary => 30000
      },{
        :area => "Handover53_62",
        :southBoundary => 31750,
        :northBoundary => 36250,
        :westBoundary => 18500,
        :eastBoundary => 19500
      },{
        :area => "Handover53_63",
        :southBoundary => 31750,
        :northBoundary => 36250,
        :westBoundary => 22000,
        :eastBoundary => 23000
      },{
        :area => "Handover54_63",
        :southBoundary => 31750,
        :northBoundary => 36250,
        :westBoundary => 25500,
        :eastBoundary => 26500
      },{
        :area => "Handover54_64",
        :southBoundary => 31750,
        :northBoundary => 36250,
        :westBoundary => 29000,
        :eastBoundary => 30000
      },{
        :area => "Common",
        :southBoundary => 6500,
        :northBoundary => 37500,
        :westBoundary => 9000,
        :eastBoundary => 29000
      }
    ]

    default[:dataGenerator] = "ipgwtg"

    # Use local IPGWTG
    #default[:ipgwtg_port] = 32000
    #default[:ipgwtg_ipAddress] = "10.10.0.1"         # IP address of the interface that can reach the PGW
    #default[:ipgwtg_inband_signaling] = false
    #default[:start_isp_simulator] = true
    #default[:ipgwtg_ftp_sender_connect_put] = true

    # Configuration of the ipgwtg user data generator,
    default[:userDataGen] = "ipex.mtu = 1436\n"
    return default
  end


  #
  # Retrieve default parameters for UBsim configuration
  #
  def Parameters.getUbsimConfigParameters()

    # Define and return default values
    default = {}

    default[:ueTypesDir] = ""              # Directory containing users UE type definitions
    default[:csTrafficModelsDir] = ""      # Directory containing users CS traffic Models
    default[:psTrafficModelsDir] = ""      # Directory containing users PS traffic Models
    default[:mobilityModelsDir] = ""       # Directory containing users Mobility Models
    default[:visualization] = false        # UBsim GUI

    # patches to use when starting UBsim
    # Given as a Java classpath, multiple element separated by ':'
    default[:ubsim_patches] = ""           # UBsim code in UBsim project (ubsim.jar)
    return default
  end


  #
  # Configure channel models
  #
  def Parameters.getChannelModelConfigParameters()
    # Define and return default values
    default = {}

    default[:model_set_name] = "default_error_set"
    default[:pdcch_drop_dl_assignment_rate] = 1.0
    default[:pdcch_drop_grant_rate] = 1.0
    default[:pdsch_transport_block_decoded_error_rate] = 1.0
    default[:phich_nack_to_ack_error_rate] = 1.0
    default[:phich_drop_harq_feedback_rate] = 1.0
    default[:pusch_transport_block_decoded_error_rate] = 1.0
    default[:pusch_drop_transport_block_rate] = 1.0
    default[:puxch_nack_to_ack_error_rate] = 1.0
    default[:puxch_dtx_to_ack_error_rate] = 1.0
    default[:puxch_ack_to_nack_error_rate] = 1.0
    default[:puxch_drop_scheduling_request_rate] = 1.0
    default[:dlni_noise] = 1.0
    default[:dlni_interference] = 1.0
    default[:dl_pathloss_min_pathloss] = 1.00
    default[:dl_pathloss_max_pathloss] = 20.0
    default[:dl_pathloss_time_min_to_max] = 1000
    default[:dl_pathloss_distribute_ues] = true
    default[:pathloss_based_feedback_sinr_threshold] = 1.0

    return default
  end
end
